{% set name = "coin3d" %}
{% set version = "4.0.1" %}
{% set sha256 = "4970051b6e0714f4207f64882dd1748e2c759ab8ebfa3e53d45703d6d3cc6512" %}
{% set superglue_version = "1.3.0" %}
{% set superglue_sha256 = "f408adcfb706e7c781db9c218ef9e8ba56d43995ccb61dffad5f6154c34f17d6" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/coin3d/coin/archive/Coin-{{ version }}.tar.gz
    sha256: {{ sha256 }}

  - url: https://github.com/coin3d/superglu/archive/superglu-{{ superglue_version }}.tar.gz
    sha256: {{ superglue_sha256 }}
    folder: superglue
    patches:
      - superglue.patch

build:
  number: 0
  skip: true  # [win and py<35]

requirements:
  build:
    - gnuconfig      # [unix]
    - {{ compiler('cxx') }}
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - {{ cdt('mesa-dri-drivers') }}      # [linux]
    - {{ cdt('libxdamage') }}      # [linux]
    - {{ cdt('libselinux') }}      # [linux]
    - {{ cdt('libXxf86vm') }}      # [linux]
    - cmake
    - ninja
  host:
    - libboost-headers
    - libglu      # [linux]
    - xorg-libxt      # [linux]
    - xorg-libxi      # [linux]
    - expat
  run:
    - libglu      # [linux]
    - xorg-libxt      # [linux]
    - xorg-libxi      # [linux]
    - expat

test:
  requires:
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  files:
    - test.cpp      # [linux]
  commands:
    - ${CXX} -o test test.cpp -Wl,-rpath-link -lCoin -L${PREFIX}/lib/ -I${PREFIX}/include/      # [linux]
    - ./test      # [linux]
    - where /r "%PREFIX%"  Coin4.dll      # [win]
    - test -f ${PREFIX}/lib/libCoin.dylib      # [osx]

about:
  home: https://bitbucket.org/Coin3D/coin/wiki/Home
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING
  summary: Coin3D is a C++ high-level 3D graphics toolkit.
  description: Coin3D is a high-level, retained-mode toolkit for effective 3D graphics development. It is API compatible with Open Inventor 2.1.
  doc_url: https://bitbucket.org/Coin3D/coin/wiki/Home
  dev_url: https://bitbucket.org/Coin3D/coin/wiki/Home

extra:
  recipe-maintainers:
    - looooo
