{% set name = "coin3d" %}
{% set version = "4.0.0" %}
{% set commit = "30674a9" %}
{% set sha256 = "2f1c9d7a14fd0be7119100673c9292014e637774277bab4550e6f78f30a205de" %}

package:
    name: {{ name }}
    version: {{ version }}

source:
    fn: {{ name }}.tar.gz
    url: https://bitbucket.org/Coin3D/coin/get/{{ commit }}.tar.gz
    sha256: {{ sha256 }}
    patches:
        - stop_the_cross_plattform_ignorance.patch

build:
    number: 1005
    skip: true  # [win and py<35]

requirements:
    build:
        - {{ compiler('cxx') }}
        - {{ cdt('mesa-libgl-devel') }}  # [linux]
        - {{ cdt('mesa-dri-drivers') }}  # [linux]
        - {{ cdt('libxdamage') }}  # [linux]
        - {{ cdt('libselinux') }}  # [linux]
        - {{ cdt('libXxf86vm') }}  # [linux]
        - cmake
        - ninja
    host:
        - boost-cpp
        - libglu  # [linux]
        - xorg-libxt  # [linux]
        - xorg-libxmu  # [linux]
        - xorg-libxi  # [linux]
        - expat
    run:
        - boost-cpp
        - libglu  # [linux]
        - xorg-libxt  # [linux]
        - xorg-libxmu  # [linux]
        - xorg-libxi  # [linux]
        - expat

test:
    requires:
        - {{ cdt('mesa-libgl-devel') }}  # [linux]
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
    files:
        - test.cpp  # [linux]
    commands:
        - ${CXX} -o test test.cpp -Wl,-rpath-link -lCoin -L${PREFIX}/lib/ -I${PREFIX}/include/  # [linux]
        - ./test  # [linux]
        - where /r "%PREFIX%"  Coin4.dll  # [win]
        - test -f ${PREFIX}/lib/libCoin.dylib  # [osx]

about:
    home: https://bitbucket.org/Coin3D/coin/wiki/Home
    license: BSD 3-Clause
    license_family: BSD
    license_file: COPYING
    summary: Coin3D is a c++ high-level 3D graphics toolkit.
    description: Coin3D is a high-level, retained-mode toolkit 
                 for effective 3D graphics development.
                 It is API compatible with Open Inventor 2.1.
    doc_url: https://bitbucket.org/Coin3D/coin/wiki/Home
    dev_url: https://bitbucket.org/Coin3D/coin/wiki/Home

extra:
    recipe-maintainers:
        - looooo
